### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by Arfor**
Changed links in homepage and in menu linking to new slug:
/answers -> /vragen

### CODE REVIEW

**Comment by SanliFaez** [comment]
I don't get this obsession with the slugs being dutch. no viewer memorizes them! 
it make the translation of the website only more difficult. I am in favor of /answers

**Comment by aquilesC** [comment]
I think we must settle this ASAP. It is either all in Dutch or all in English, but mixing creates a bad user experience. I am in favor of having all in Dutch for the dutch website, if we ever go into translating, then the slugs can be automatically translated. Sadly, the people at Fabrique made a mess mixing strings in english and in dutch all over the templates, with a bit of time this can be figured out.

**Review by aquilesC — CHANGES_REQUESTED** [review]
These changes are not engouh to ensure the proper structure of the website. `/answers`` are used, for example, in **answer_detail.html**

**Review by SanliFaez — APPROVED** [review]

**Comment by SanliFaez** [comment]
okay, I am convinced. we do it in dutch and I will be careful if any other pages need that.

**Comment by Arfor** [comment]
Oke, then maybe fixing all the slugs at the same time would be a better idea. We also have /ask, which would unfortunately translate to "/vraag" and /about -> /over.
I'd suggest /ask -> /stel-je-vraag.

**Pull request closed without merging**
