### PR TITLE
Updated format for gitlab issue description

### PR DESCRIPTION
**Pull request by Arfor**
- Issue title -> Add "Question: ", since that has to be deleted in the question to use in the /in_behandeling page.
- Issue description -> changed to multiline f-string to automatically make the description coherent with the rest of the issues on the gitlab

### CODE REVIEW

**Review by aquilesC — CHANGES_REQUESTED** [review]
Bear in mind that the ``original_question`` may be blank unless someone copies it before approving, and that the question in the title is limited to 255 characters. Therefore there may be some missing information at the moment of creating the question. 

Also, there may be one missing newline before the list (you need one empty line to generate proper markdown lists).

**Comment by Arfor** [comment]
Thanks for checking! I missed the 255 character limit indeed. `len(Question: )=10` so I changed it to 244.

If a blank field doesn't throw an error, then I guess it's fine. There was one other thing I wanted to do: if the user_email=empty then write "anonymous", but I didn't want to break anything so I didn't try it. It's also not very important, we can just say that if it's empty, it's anonymous.

In GitLab the list seems to work without having a blank line, so I left that as is.

**Review by aquilesC — CHANGES_REQUESTED** [review]
Sorry, I was not clear with what I wanted to say. 

``issue_title[:254]`` was OK, it trims the title of the issue to 255 characters _including_ the ``'Question: '``. So there was no problem in there. 

My concern is that self.question.question is only stored in the title of the issue. If the question is long it will be trimmed. ``original_question`` is optional, which means there's a high likelyhood of data loss. ``question.question`` should be put back to the issue body, as it was. ``original_question`` can be _added_, but it can't substitute ``question``.

**Comment by Arfor** [comment]
Oops, yep the splicing is after the definition, nvm. I see what you mean, I've added back self.question.question on top of the description.
Sorry for this back and forth

**Comment by aquilesC** [comment]
No problems! It is useful to have the back and forth to get used to the code, etc. thought it was a better idea than just fixing it myself.

**Pull request merged**
